# Generated by Django 4.2.7 on 2023-12-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, choices=[('a', 'Housing'), ('b', 'Transportation'), ('c', 'Food'), ('d', 'Utilities'), ('e', 'Clothing'), ('f', 'Medical/Healthcare'), ('g', 'Insurance'), ('h', 'Household Items/Supplies'), ('i', 'Personal'), ('j', 'Debt'), ('k', 'Retirement'), ('l', 'Education'), ('m', 'Savings'), ('n', 'Gifts/Donations'), ('r', 'Entertainment'), ('o', 'Other')], help_text='Categories', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
